#!//bin/bash
#sudo yum -y update
sudo yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
sudo yum --enablerepo=remi install redis -y
sudo systemctl enable --now redis

sudo grep "^requirepass" /etc/redis/redis.conf

if [[ $? -eq 0 ]];then
  sudo sed -i 's/^requirepass.*/requirepass superMan1/g' /etc/redis/redis.conf
else
  sudo sed -i 's/^# requirepass.*/requirepass superMan1/g' /etc/redis/redis.conf
fi

sudo sed -i 's/^bind.*/bind * -::*/g' /etc/redis/redis.conf

sudo systemctl restart redis

stat=$(sudo systemctl status redis | grep Active: | awk '{print $2}')
if [ $stat == "active" ];then
        echo "INSTALL COMPLETE"
else
        echo "INSTALL INCOMPLETE"
fi
